### PR TITLE
Register discovered Kubernetes instance clusters with Turbine

### LINKED ISSUE #24: Turbine stream not working for clusters discovered by KubernetesInstanceDiscovery
It's actually two issues, but they are related:

1. If I configure breakerbox to use `KubernetesInstanceDiscovery`, the `YamlInstanceDiscovery` still seems to be active. Is there a reason for that? This seems confusing and can lead to errors in the configuration if users just leave out the 'turbine' field in their yaml file.
2. The metrics dashboard only works for those clusters that are specified via yaml. Clusters disovered by `KubernetesInstanceDiscovery` lead to the following:

`"GET /turbine.stream?cluster=staging-auth-facade&delay=1000 HTTP/1.1" 404` (Cluster not found). Am I missing something here?

### PR DESCRIPTION
**Pull request by mlamina**
Fixes #24

### CODE REVIEW

**Comment by chrisgray** [comment]
Did you mean to have your Dockerfile as part of the PR?

**Comment by mlamina** [comment]
No I didn't! I just used that for testing everything in my cluster. But regarding that topic: Would it be possible to have a docker image for the current snapshot release?

**Comment by chrisgray** [comment]
Definitely! Feel free to submit a PR

**Comment by mlamina** [comment]
I'd love to, but I am not sure what your CI process looks like, hence what a Dockerfile would look like that automatically triggers a new snapshot image with every commit on master?

**Comment by chrisgray** [comment]
We have an internal branch that is forked from here that has our own InstanceDiscovery mechanism as well as Dockerfile too. Breakerbox here on github.com builds on travis-ci.org so as long as that Dockerfile instance can publish to a public registry we should be fine. So we should be fine!

**Comment by chrisgray** [comment]
Followed up your commit so that now all `InstanceDiscovery` instances will register clusters without having to explicitly do so. I'll cut a release so that this will be available in Breakerbox 0.4.5 as well.

https://github.com/yammer/breakerbox/commit/31a1b349f30af2741fc48d07246bcc2f272e37b0

**Comment by mlamina** [comment]
OK, just to make sure I get this right: Should I just create a pull request containing a Dockerfile in the root directory that will build an image using whatever fat jar is in the target directory?

**Comment by chrisgray** [comment]
Feel free to use the docker branch I just created. It has an additional step when shading so a jar is created without the snapshot/release version so it's easier to use it with a script. I've also added a step to where it'll copy it to docker/breakerbox.jar:

https://github.com/yammer/breakerbox/commit/1f29a951b47b0983cdc982d089e9cba455acd001

**Pull request merged**
